import './globals.css'
import { Rubik } from 'next/font/google'

// components
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Agung Darmawan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        <main className='app-content'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
